name: "Terraform PRO Pipeline"

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  terraform-plan:
    name: "1. Inspection (Plan)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ÉTAPE CLÉ : Authentification officielle
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - uses: hashicorp/setup-terraform@v3
      
      - name: Init & Plan
        run: |
          terraform init
          terraform plan -out=tfplan
          
  terraform-apply:
    name: "2. Déploiement (Apply)"
    needs: terraform-plan
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - uses: hashicorp/setup-terraform@v3
      
      - name: Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve