# ==========================================================================
# PIPELINE CI/CD TERRAFORM PRO (Version Multi-Dossiers)
# ==========================================================================
name: "Terraform PRO Pipeline"

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  terraform-plan:
    name: "1. Inspection (Plan)"
    runs-on: ubuntu-latest
    # Cette option force toutes les commandes 'run' à s'exécuter dans ce dossier
    defaults:
      run:
        working-directory: ./02-infrastructure 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init & Plan
        run: |
          terraform init
          terraform plan -out=tfplan

      - name: Archive Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          # On précise le chemin relatif au working-directory
          path: 02-infrastructure/tfplan
          retention-days: 1
          
  terraform-apply:
    name: "2. Déploiement (Apply)"
    needs: terraform-plan
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./02-infrastructure

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          # On télécharge l'artefact directement dans le dossier de travail
          path: 02-infrastructure
      
      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve tfplan